export default {
  asset: '私の現在の資産',
  title: 'プールに寄付',
  performance: '業績',
  link: 'リンク',
  rule: 'I LAFマーケットメーカー投資規則',
  tip: 'プールに寄付後、寄付額に応じて1日最大1.2%の自動複利、1回あたり最大30元。',
  tab1: '投資リスト',
  tab2: '償還リスト',
  confirmInviter: '招待者を確認',
  address: '招待者のアドレスを入力してください',
  addAsset: '資産を追加',
  inputIncreaseAmount: '増加金額を入力してください',
  option1: '1日、複利0.3%',
  option2: '15日、複利0.6%',
  option3: '30日、複利1.2%',
  selectDays: '日数を選択してください',
  cancel: 'キャンセル',
  confirm: '確定',
  index: '番号',
  date: '日付',
  principal: '元本',
  profit: '利益',
  action: '償還進行状況'
};
